version: 2.1

jobs:
  test:
    parameters:
      ruby:
        type: string
      rails:
        type: string
      postgres:
        type: string
    docker:
      - image: << parameters.ruby >>
        environment:
          BUNDLE_GEMFILE: gemfiles/<< parameters.rails >>.gemfile
      - image: cimg/<< parameters.postgres >>
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              ruby: ['ruby:3.0', 'ruby:3.1', 'ruby:3.2']
              rails: ['rails_6.1', 'rails_7.0', 'rails_7.1']
              postgres: ['postgres:11.21', 'postgres:12.16', 'postgres:13.12', 'postgres:14.9', 'postgres:15.4']
