version: 2.1

jobs:
  test:
    parameters:
      ruby:
        type: string
      rails:
        type: string
      postgres:
        type: string
    docker:
      - image: << parameters.ruby >>
      - image: cimg/<< parameters.postgres >>
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec appraisal << parameters.rails >> bundle install
      - run: bundle exec appraisal << parameters.rails >> rspec

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              ruby: ['ruby:2.7', 'ruby:3.0', 'ruby:3.1']
              rails: ['rails-6.0', 'rails-6.1', 'rails-7.0']
              postgres: ['postgres:11.13', 'postgres:12.9', 'postgres:13.5', 'postgres:14.1']
